fixtures:
  repositories:
    stdlib:  'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat:  'https://github.com/puppetlabs/puppetlabs-concat.git'
    systemd: 'https://github.com/voxpupuli/puppet-systemd.git'
